#!/usr/bin/env ruby

require 'pathname'

$: << '.'
if File.symlink?(__FILE__)
    $: << File.dirname(Pathname.new(File.dirname(__FILE__)) + File.readlink(__FILE__))
else
    $: << File.dirname(__FILE__)
end

if ARGV.size > 0
    name = ARGV[0]
else
    name = "tests"
end
def do_file(file, short_name)
    print "#{short_name}: "
    require file
    puts "Survived"
end
if Dir.exist? name
    puts "Got dir #{name}"
    Dir.glob("#{name}/*_[0-9]*").sort.each {|file|
	short_name = file.sub(/^#{name}\//, "")
	pid = fork {
	    do_file(file, short_name)
	}
	Process.wait pid
    }
else
    do_file(name, name)
end
